/* Export and sharing: Markdown, plain text, JSON and the raw audio file. */

import { fmtClock, fmtDate, fmtDuration } from './util.js';
import { getAudio } from './db.js';

function speakerName(meeting, seg) {
  if (!seg.speaker) return '';
  return (meeting.speakers || {})[seg.speaker] || seg.speaker;
}

/** Title for exports and filenames, where the date is worth carrying. */
export function meetingTitle(meeting) {
  return meeting.title || meeting.analysis?.title || `Recording — ${fmtDate(meeting.createdAt)}`;
}

/** Title for on-screen headings, which already sit next to the date. */
export function displayTitle(meeting) {
  return meeting.title || meeting.analysis?.title || 'Untitled recording';
}

export function toMarkdown(meeting, { includeTranscript = true } = {}) {
  const a = meeting.analysis;
  const lines = [];
  lines.push(`# ${meetingTitle(meeting)}`, '');
  lines.push(`*${fmtDate(meeting.createdAt)} · ${fmtDuration(meeting.durationMs)} · ${meeting.source === 'call' ? 'Phone call' : 'Microphone'}*`, '');

  if (a) {
    if (a.summary) lines.push('## Summary', '', a.summary, '');
    if (a.keyPoints?.length) {
      lines.push('## Key points', '');
      a.keyPoints.forEach((p) => lines.push(`- ${p}`));
      lines.push('');
    }
    if (a.decisions?.length) {
      lines.push('## Decisions', '');
      a.decisions.forEach((d) => lines.push(`- ${d}`));
      lines.push('');
    }
    if (a.actionItems?.length) {
      lines.push('## Action items', '');
      a.actionItems.forEach((item) => {
        const bits = [item.owner && item.owner !== 'Unassigned' ? `**${item.owner}**` : null, item.due || null]
          .filter(Boolean).join(' · ');
        lines.push(`- [${item.done ? 'x' : ' '}] ${item.task}${bits ? ` — ${bits}` : ''}`);
      });
      lines.push('');
    }
    if (a.openQuestions?.length) {
      lines.push('## Open questions', '');
      a.openQuestions.forEach((q) => lines.push(`- ${q}`));
      lines.push('');
    }
    if (a.topics?.length) lines.push(`**Topics:** ${a.topics.join(', ')}`, '');
    if (a.followUpEmail) lines.push('## Recap email draft', '', a.followUpEmail, '');
  }

  if (includeTranscript && meeting.segments?.length) {
    lines.push('## Transcript', '');
    for (const seg of meeting.segments) {
      const who = speakerName(meeting, seg);
      lines.push(`**[${fmtClock(seg.start)}]${who ? ` ${who}:` : ''}** ${seg.text}`, '');
    }
  }

  lines.push('---', '', `_Generated by Summary${a?.provider === 'anthropic' ? ` using ${a.model}` : ' (on-device analysis)'}._`);
  return lines.join('\n');
}

export function toPlainText(meeting) {
  return toMarkdown(meeting)
    .replace(/^#{1,6}\s*/gm, '')
    .replace(/\*\*/g, '')
    .replace(/^\*(.+)\*$/gm, '$1');
}

export function toJson(meeting) {
  return JSON.stringify(meeting, null, 2);
}

function slug(text) {
  return String(text).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 60) || 'recording';
}

export function baseFilename(meeting) {
  const d = new Date(meeting.createdAt);
  const stamp = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
  return `${stamp}-${slug(meetingTitle(meeting))}`;
}

export function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.append(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 10_000);
}

export function downloadText(text, filename, type = 'text/markdown') {
  downloadBlob(new Blob([text], { type: `${type};charset=utf-8` }), filename);
}

export async function downloadAudio(meeting) {
  const blob = await getAudio(meeting.id);
  if (!blob) return false;
  const ext = (blob.type.includes('mp4') && 'm4a') || (blob.type.includes('ogg') && 'ogg') || 'webm';
  downloadBlob(blob, `${baseFilename(meeting)}.${ext}`);
  return true;
}

export async function copyToClipboard(text) {
  if (navigator.clipboard?.writeText) {
    await navigator.clipboard.writeText(text);
    return true;
  }
  // Fallback for browsers without the async clipboard API.
  const ta = document.createElement('textarea');
  ta.value = text;
  ta.style.position = 'fixed';
  ta.style.opacity = '0';
  document.body.append(ta);
  ta.select();
  const ok = document.execCommand?.('copy');
  ta.remove();
  return Boolean(ok);
}

export function canShare() {
  return Boolean(navigator.share);
}

/** Android's share sheet — text by default, with the audio file when supported. */
export async function shareMeeting(meeting, { withAudio = false } = {}) {
  const text = toMarkdown(meeting, { includeTranscript: false });
  const title = meetingTitle(meeting);

  if (withAudio) {
    const blob = await getAudio(meeting.id);
    if (blob) {
      const ext = (blob.type.includes('mp4') && 'm4a') || (blob.type.includes('ogg') && 'ogg') || 'webm';
      const file = new File([blob], `${baseFilename(meeting)}.${ext}`, { type: blob.type || 'audio/webm' });
      if (navigator.canShare?.({ files: [file] })) {
        await navigator.share({ title, text, files: [file] });
        return true;
      }
    }
  }
  await navigator.share({ title, text });
  return true;
}
